Debug: false
Language: Chinese
bStats: false

Settings:
  # 被篝火治疗的范围, 应该是半径
  Distance: 4
  # 被篝火治疗的生命值上限比例
  # 例如 0.8 是最高能被治疗到最大生命值的 80%
  MaxRegen: 0.7
  # 被篝火治疗的血量
  Regen: "1~3"
  # 每隔多少秒回一次血
  Cycle: 2.5
  # 被篝火回血后多少秒内不能再被篝火回血
  # 该设置是为了避免被篝火重复回血用的
  # 大概期望一个比上面的回血循环时间稍小的值
  # 要想故意让玩家错开回血循环也可以搞一个稍大的值
  Cooldown: 2
Sentences:
  - "你感觉你的身体舒适了很多..."
  - "你感觉你又充满了干劲..."
  - "你感觉你又脉动了回来("
  - "你感觉你的状态又回来了..."
  - "你感到非常的暖和..."